substitutions:
  _TAG: 'latest'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/practice-repo/app:$_TAG'
      - '.'
    id: 'build-image'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/practice-repo/app:$_TAG'
    id: 'push-image'
    waitFor: ['build-image']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'practice-service'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/practice-repo/app:$_TAG'
      - '--region=us-central1'
      - '--service-account=cloud-run-runtime@$PROJECT_ID.iam.gserviceaccount.com'
      - '--quiet'
    id: 'deploy'
    waitFor: ['push-image']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/practice-repo/app:$_TAG'

options:
  logging: CLOUD_LOGGING_ONLY
